apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: ocs
spec:
  machineConfigSelector:
    matchExpressions:
      - values:
          - worker
          - ocs
        operator: In
        key: machineconfiguration.openshift.io/role
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ocs: ""