#  ____  __.               __                 .__
# |    |/ _|__ __  _______/  |_  ____   _____ |__|_______ ____
# |      < |  |  \/  ___/\   __\/  _ \ /     \|  \___   // __ \
# |    |  \|  |  /\___ \  |  | (  <_> )  Y Y  \  |/    /\  ___/
# |____|__ \____//____  > |__|  \____/|__|_|  /__/_____ \\___  >
#         \/          \/                    \/         \/    \/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - overlay/cicd
  - overlay/quarkus-example