# Default log retention
.defaults:
 delete:
   days: 1

# Log retention for operations index
.operations:
 delete:
   days: 1

# Log retention for applications index
.regex:
  - pattern: '^project\..*$'
    delete:
      days: 7
