apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
    - name: container-one
      image: ubi8/ubi-minimal:8.1-407
      imagePullPolicy: IfNotPresent
      entrypoint: sh
      command:
        - sleep
        - "3600"
    - name: container-two
      image: ubi8/ubi-minimal:8.1-407
      imagePullPolicy: IfNotPresent
      entrypoint: sh
      command:
        - sleep
        - "3600"
  restartPolicy: Always
