apiVersion: v1
kind: Namespace
metadata:
  name: openshift-metering
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
spec:
  finalizers:
  - kubernetes
