# Manual deployments
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: apps-deployers
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: developer-a
