global:
  resolve_timeout: 5m
receivers:
  - name: default
    email_configs:
      - to: '<devops@example.io>'
        from: '<noreply@example.io>'
        smarthost: 'smtp-fake-server.openshift-monitoring.svc.cluster.local:9025'
        auth_username: 'alertmanager'
        auth_password: 'Alerts1234'
        require_tls: true
        tls_config:
          insecure_skip_verify: true
        send_resolved: true
  - name: watchdog
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
    - match:
        alertname: Watchdog
      repeat_interval: 5m
      receiver: watchdog

