kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-example-file
spec:
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs