apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-images-0
  labels:
    app: registry
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-cephfs