apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: operator-metering
spec:
  reporting-operator:
    spec:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 100Mi
  hive:
    spec:
      metastore:
        resources:
          limits:
            cpu: "4"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 650Mi
        storage:
          class: ocs-storagecluster-ceph-rbd
          size: 5Gi
      server:
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
  presto:
    spec:
      coordinator:
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 2Gi
      worker:
        replicas: 0
        resources:
          limits:
            cpu: "8"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 2Gi
  storage:
    type: hive
    hive:
      type: sharedPVC
      sharedPVC:
        storageClass: ocs-storagecluster-cephfs
        createPVC: true
        size: 10Gi
  permissions:
    # This also gives permissions query the results from the reporting REST API.
    reportingViewers:
    - kind: ServiceAccount
      name: reports-viewer
      namespace: openshift-metering
