apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
bases:
  - ../../base
resources:
  - manifests/namespace.yml
  - manifests/quota.yml
  - manifests/sa-cicd-deployer-root.yml
