apiVersion: v1
kind: Pod
metadata:
  name: ubi8
spec:
  containers:
    - name: shell1
      image: ubi8
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      env:
        - name: CUSTOM_UBI_CONFIG
          valueFrom:
            configMapKeyRef:
              name: ubi-config
              key: config.properties
        - name: MAX_MEMORY
          value: "60MB"
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
    - name: shell2
      image: ubi8
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/ubi-config
          subPath: config.properties
  volumes:
    - name: config-volume
      configMap:
        name: ubi-config
  restartPolicy: Always
