apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: namespace-cpu-utilization-monthly
  namespace: openshift-metering
  labels:
    report-frequency: monthly
spec:
  query: namespace-cpu-utilization
  schedule:
    period: cron
    expression: "0 0 1 * *"
