apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: elasticsearch
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      storage:
        storageClassName: gp2
        size: 50G
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      resources:
        limits:
          cpu: "1"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "8Gi"
  visualization:
    type: kibana
    kibana:
      replicas: 1
    nodeSelector:
      node-role.kubernetes.io/infra: ""
  curation:
    type: curator
    curator:
      schedule: 30 3 * * * # Every day at At 03:30
    nodeSelector:
      node-role.kubernetes.io/infra: ""
  collection:
    logs:
      type: fluentd
      fluentd:
        resources:
          limits:
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "1Gi"
